spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5440}/${POSTGRES_DB:traveloka}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          time_zone: UTC
        cache:
          use_second_level_cache: false
      jakarta.persistence.schema-generation.scripts.action: create
      jakarta.persistence.schema-generation.scripts.create-target: target/schema-from-entities.sql

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    schemas: iam, inventory, availability, pricing, booking, payment, review, notify, geo

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2

  cache:
    type: redis
    redis:
      time-to-live: 1800000  # 30 minutes
      cache-null-values: false
      key-prefix: "traveloka:"
      use-key-prefix: true

  session:
    store-type: redis
    redis:
      namespace: "traveloka:session"
    timeout: 86400s # 24 hours

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${KEYCLOAK_HTTP_PORT:8081}/realms/cena
          jwk-set-uri: http://localhost:${KEYCLOAK_HTTP_PORT:8081}/realms/cena/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 60MB

minio:
  endpoint: http://localhost:${MINIO_PORT:9000}
  accessKey: ${MINIO_ROOT_USER:minio}
  secretKey: ${MINIO_ROOT_PASSWORD:minio123}
  bucket: images
  external-url: http://localhost:9000

# Keycloak Admin Client Configuration
keycloak:
  admin:
    realm: cena
    server-url: http://localhost:${KEYCLOAK_HTTP_PORT:8081}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    pool-size: 10
    connection-timeout: 5000ms
    socket-timeout: 5000ms

# IAM Module Configuration
traveloka:
  iam:
    enabled: true
    keycloak:
      server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
      realm: ${KEYCLOAK_REALM:traveloka}
      admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
      admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
      connection-pool-size: 10
    session:
      max-concurrent-sessions: 5
      session-timeout: 86400s # 24 hours
      cleanup-interval: 3600s # 1 hour
      concurrent-session-control: true
    cache:
      user-profile-ttl: 1800s # 30 minutes
      session-ttl: 900s # 15 minutes
      role-permissions-ttl: 3600s # 1 hour
      sync-events-ttl: 300s # 5 minutes
    sync:
      enabled: true
      batch-size: 100
      max-retries: 3
      retry-delay-minutes: 5
      cleanup:
        success-retention-days: 7
        failed-retention-days: 30
    security:
      cors:
        allowed-origins: "http://localhost:3000,http://localhost:3001"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true
      rate-limiting:
        auth-requests-per-minute: 10
        profile-requests-per-minute: 30
        session-requests-per-minute: 20
  performance:
    database:
      query-timeout: 30000
      connection-validation-timeout: 5000
    cache:
      default-ttl: 1800
      max-entries: 10000

